services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    whatwedo\MonitorBundle\:
        resource: '../../*'
        exclude:
            - '../../DependencyInjection/'
            - '../../Enum/'

    whatwedo\MonitorBundle\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    whatwedo\MonitorBundle\Normalizer\:
        resource: '../../Normalizer/'
        tags: ['serializer.normalizer']

    whatwedo\MonitorBundle\Monitoring\Metric\Messenger\QueuedMessages:
        arguments:
            $receiverLocator: '@?messenger.receiver_locator'
            $failureTransport: '@?messenger.failure_transports.default'

    whatwedo\MonitorBundle\Monitoring\Sensor\Database\DoctrineMigrations:
        arguments: ['@?doctrine.migrations.dependency_factory']
