name: whatwedoMonitorBundle

on:
    push: ~
    pull_request: ~

jobs:
    phpunit:
        runs-on: ${{ matrix.operating-system }}
        name: PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }} on ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ ubuntu-latest ]
                php: [ '8.4', '8.5' ]
                symfony: [ '7.4.*', '8.0.*', '8.1.*' ]

        steps:
            - uses: actions/checkout@master

            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: xdebug
                  tools: flex

            - name: Download dependencies
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony }}
              uses: ramsey/composer-install@v1

            - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
              env:
                  XDEBUG_MODE: coverage
              run: vendor/bin/simple-phpunit --configuration phpunit.xml.dist tests --coverage-clover ./coverage.xml

            - name: Upload to Codecov
              uses: codecov/codecov-action@v2
              with:
                files: ./coverage.xml
                verbose: true

    qa:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Download dependencies
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony }}
              uses: ramsey/composer-install@v1

            - name: Initialize simple-phpunit
              run: vendor/bin/simple-phpunit --version

            - name: Check Code Styles
              run: vendor/bin/ecs

            - name: Check PHPStan
              run: vendor/bin/phpstan analyse src tests
